version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.1
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  go_cache:
  go_build:
  influxdb_data:
