version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.1
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken

volumes:
  go_cache:
  go_build:
  influxdb_data:
